config/routes.rb
Kir::Application.routes.draw do

  constraints subdomain: /ru|en/ do
    resources :apps, only: [:index, :show] do
      resources :surveys, only: [:index, :show] do
        resources :variants do
          get :upvote, on: :member
        end
      end
    end

    match 'sitemap' => 'info#sitemap', via: :get
    match 'feedback' => 'feedback#feedback', via: :get
    match 'send_feedback' => 'feedback#send_feedback', via: :post

    constraints :slug => /#{StaticPage.slug.values.join('|')}/ do
      match ':slug' => 'static_pages#show', via: :get
    end

    root 'apps#index'
  end

  root 'info#start', as: :start
  devise_for :users

  namespace :admin do
    resources :apps
    resources :surveys
    resources :static_pages

    match 'video' => 'video#show', via: :get
    root 'apps#index'
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  default_scope -> { order(:app_id).order(:id) }

  belongs_to :app
  has_many :variants

  translates :question, fallbacks_for_empty_translations: true

  accepts_nested_attributes_for :variants, allow_destroy: true
  accepts_nested_attributes_for :translations

end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::AdminController
  load_and_authorize_resource

  def index
  end

  def new
    available_locales.each{ |locale| @survey.translations.build(locale: locale) }
  end

  def create
    @survey = Survey.create(survey_params)
    respond_with @survey, location: admin_surveys_path
  end

  def edit
    available_locales.each{ |locale| @survey.translations.find_or_initialize_by_locale(locale) }
  end

  def update
    @survey.update_attributes(survey_params)
    respond_with @survey, location: admin_surveys_path
  end

  private

    def survey_params
      params.require(:survey).permit(:app_id, :multiple, :active, variants_attributes: [:id, :text, :_destroy], translations_attributes: [:id, :locale, :question] )
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  load_and_authorize_resource :app
  load_and_authorize_resource :survey, through: :app
  def index
    respond_to do |format|
      format.json { render(json: @surveys.to_json) }
    end
  end

end

app/views/admin/surveys/_form.html.slim
= simple_nested_form_for [:admin, @survey] do |f|
  ul.nav.nav-tabs
    - available_locales.each do |i_locale|
      li class="#{(i_locale == current_locale) ? 'active' : ''}"
        = link_to i_locale, "##{i_locale}", 'data-toggle' => "tab"
  .tab-content
    = f.simple_fields_for :translations, wrapper: false do |g|
      .tab-pane id=g.object.locale class="#{(g.object.locale == current_locale) ? 'active' : ''}"
        = g.input :id, as: :hidden
        = g.input :locale, as: :hidden
        = g.input :question
  = f.association :app, include_blank: false
  = f.input :multiple
  = f.input :active
  = f.simple_fields_for :variants do |v|
    = v.input :text
    = v.link_to_remove 'Remove'
  = f.link_to_add 'Add', :variants
  = f.submit

app/views/admin/surveys/edit.html.slim
= render 'form'

app/views/admin/surveys/index.html.slim
= link_to 'New', new_admin_survey_path, class: 'btn btn-info'
table.table.table-bordered.table-striped
  tr
    th App
    th Question
    th Multiple
    th Active
    th Actions
  - @surveys.each do |survey|
    tr
      td = link_to survey.app.title, admin_app_path(survey.app)
      td = survey.question
      td = survey.multiple
      td = survey.active
      td
        .btn-group
          = link_to 'Edit', edit_admin_survey_path(survey), class: 'btn btn-warning'
          = link_to 'Destroy', admin_survey_path(survey), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'

app/views/admin/surveys/new.html.slim
= render 'form'