config/routes.rb
Kir::Application.routes.draw do

  constraints subdomain: /ru|en/ do
    resources :apps, only: [:index, :show] do
      resources :surveys, only: [:index, :show] do
        resources :variants do
          get :upvote, on: :member
        end
      end
    end

    match 'sitemap' => 'info#sitemap', via: :get
    match 'feedback' => 'feedback#feedback', via: :get
    match 'send_feedback' => 'feedback#send_feedback', via: :post

    constraints :slug => /#{StaticPage.slug.values.join('|')}/ do
      match ':slug' => 'static_pages#show', via: :get
    end

    root 'apps#index'
  end

  root 'info#start', as: :start
  devise_for :users

  namespace :admin do
    resources :apps
    resources :surveys
    resources :static_pages

    match 'video' => 'video#show', via: :get
    root 'apps#index'
  end
end

app/views/admin/apps/_form.html.slim
= simple_form_for [:admin, @app], html: { class: 'form-horizontal' } do |f|
  ul.nav.nav-tabs
    - available_locales.each do |i_locale|
      li class="#{(i_locale == current_locale) ? 'active' : ''}"
        = link_to i_locale, "##{i_locale}", 'data-toggle' => "tab"
  .tab-content
    = f.simple_fields_for :translations do |g|
      .tab-pane id=g.object.locale class="#{(g.object.locale == current_locale) ? 'active' : ''}"
        = g.input :id, as: :hidden
        = g.input :locale, as: :hidden
        = g.input :title
        = g.input :info
  = f.input :google_name
  = f.input :background
  = f.input :download_url
  = f.submit

app/views/admin/apps/edit.html.slim
= render 'form'

app/views/admin/apps/index.html.slim
= link_to 'New', new_admin_app_path, class: 'btn btn-info btn-xs'
br
br
table.table.table-bordered.table-striped
  tr
    th Title
    th Info
    th image
    th Download url
    th Actions
  - @apps.each do |app|
    tr
      td = app.title
      td = app.info
      td = image_tag(app.background.url(:medium))
      td
        - if app.download_url.present?
          = link_to app.download_url
        - else
          = "No link provided"
      td
        .btn-group-vertical.btn-group-xs
          = link_to 'Edit', edit_admin_app_path(app), class: 'btn btn-warning'
          = link_to 'Destroy', admin_app_path(app), data: { method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger'

app/views/admin/apps/new.html.slim
= render 'form'