config/routes.rb
Kir::Application.routes.draw do

  constraints subdomain: /ru|en/ do
    resources :apps, only: [:index, :show] do
      resources :surveys, only: [:index, :show] do
        resources :variants do
          get :upvote, on: :member
        end
      end
    end

    match 'sitemap' => 'info#sitemap', via: :get
    match 'feedback' => 'feedback#feedback', via: :get
    match 'send_feedback' => 'feedback#send_feedback', via: :post

    constraints :slug => /#{StaticPage.slug.values.join('|')}/ do
      match ':slug' => 'static_pages#show', via: :get
    end

    root 'apps#index'
  end

  root 'info#start', as: :start
  devise_for :users

  namespace :admin do
    resources :apps
    resources :surveys
    resources :static_pages

    match 'video' => 'video#show', via: :get
    root 'apps#index'
  end
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  translates :content, fallbacks_for_empty_translations: true

  extend Enumerize

  enumerize :slug, in: [:about]

  validates :slug, presence: true, uniqueness: true

  accepts_nested_attributes_for :translations

end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < Admin::AdminController
  load_and_authorize_resource

  def index
  end

  def new
    available_locales.each{ |locale| @static_page.translations.build(locale: locale) }
  end

  def create
    @static_page = StaticPage.create(static_page_params)
    respond_with @static_page, location: admin_static_pages_path
  end

  def edit
    available_locales.each{ |locale| @static_page.translations.find_or_initialize_by_locale(locale) }
  end

  def update
    @static_page.update_attributes(static_page_params)
    respond_with @static_page, location: admin_static_pages_path
  end

  private

    def static_page_params
      params.require(:static_page).permit(:slug, { translations_attributes: [:id, :locale, :content] })
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # load_and_authorize_resource

  def show
    @static_page = StaticPage.find_by_slug(params[:slug])
    if request.xhr?
      respond_to do |format|
        format.json { render(json: @static_page.to_json)}
      end
    else
      render text: '', layout: true
    end
  end

end

app/views/admin/static_pages/_form.html.slim
= simple_form_for [:admin, @static_page] do |f|
  ul.nav.nav-tabs
    - available_locales.each do |i_locale|
      li class="#{(i_locale == current_locale) ? 'active' : ''}"
        = link_to i_locale, "##{i_locale}", 'data-toggle' => "tab"
  .tab-content
    = f.simple_fields_for :translations do |g|
      .tab-pane id=g.object.locale class="#{(g.object.locale == current_locale) ? 'active' : ''}"
        = g.input :id, as: :hidden
        = g.input :locale, as: :hidden
        = g.input :content, as: :ckeditor
  = f.input :slug, include_blank: false
  = f.submit

app/views/admin/static_pages/edit.html.slim
= render 'form'

app/views/admin/static_pages/index.html.slim
= link_to 'New', new_admin_static_page_path, class: 'btn btn-info'
table.table.table-bordered.table-striped
  tr
    th Title
    th Actions
  - @static_pages.each do |page|
    tr
      td = page.slug
      td
        .btn-group
          = link_to 'Edit', edit_admin_static_page_path(page), class: 'btn btn-warning'
          = link_to 'Destroy', admin_static_page_path(page), data: { method: :delete, confirm: 'Are you sure?'}, class: 'btn btn-danger'

app/views/admin/static_pages/new.html.slim
= render 'form'